FairwindsOps/pluto

README.md
ROADMAP.md
cmd/root.go

Fix a couple typos. Change klog to println when no command is passed

Updating documentation.

---

README.md
cmd/root.go

Changing show-non-deprecated to show-all

---

pkg/helm/helm.go
pkg/helm/helm_test.go

There was a strange bug that only manifested in actual usage, not in unit tets. Secret list wires were getting crossed with pointers. I made them not pointers.

Fix bug with secrets list

---

pkg/api/versions.go
pkg/helm/helm.go

better error messaging of duplicate yaml key in helm manifest data

---

README.md
ROADMAP.md

- Removing helm 2 from roadmap since it is implemented
- adding proper CI link to CircleCI badge

Documentation update

---

pkg/helm/helm.go
pkg/helm/helm_test.go

catch errors from helm client

---

README.md
cmd/root.go
pkg/api/list.go
pkg/api/list_test.go
pkg/api/output.go
pkg/api/output_test.go
pkg/api/versions.go
pkg/api/versions_test.go
pkg/finder/finder_test.go
pkg/helm/helm_test.go

This pull request addresses issue #20.
This worked for the use cases I had but might not fit what you have in mind. Feel free to reject.
**Note**: The deprecations for Istio are to by best knowledge but I was unable to find an exhaustive list of deprecations.

Add Support for Istio and cert-manager

---

README.md
cmd/root.go
e2e/tests/00_static_files.yaml
e2e/tests/02_helm-detect-2.yaml
pkg/api/output.go
pkg/api/output_test.go
pkg/api/versions.go
pkg/finder/finder_test.go
pkg/helm/helm_test.go

Fixes #99
Also removed some error passing that was impossible to hit.

Fix return message when no known versions are parsed. Remove show-all

---

go.mod
go.sum

update pkger to 0.17.1

---

.goreleaser.yml

And other stuff added to goreleaser
Fixes #119

Ensure binary is statically linked

---

README.md
ROADMAP.md
cmd/root.go
e2e/tests/02_helm-detect-2.yaml
pkg/helm/helm.go

Add deprecation warnings for Helm 2

---

README.md

fixes #110
I can add the Issue and Pull Request templates after this is in and reference the FAQ section where necessary.

adding faq to README

---

versions.yaml

updates to versions.yaml for 1.22 deprecations

---

versions.yaml

update ingress deprecations and removals

---

.circleci/config.yml
.goreleaser.yml
Makefile

Fixes #202 
Adding a Makefile and goreleaser entry for building windows binaries.

Windows build support

---

.circleci/config.yml
.gitignore
Makefile
docs/.vuepress/config-extras.js
docs/contributing/guide.md
docs/orb.md
orb/@orb.yml
orb/commands/detect.yml
orb/commands/detect_files.yml
orb/examples/detect.yml
orb/examples/detect_files.yml
orb/executors/default.yml
orb/jobs/detect.yml
orb/jobs/detect_files.yml
orb/scripts/detect.sh
orb/scripts/detect_files.sh
release-orb.sh

Creating a circleci orb for Pluto which includes the `detect` and `detect-files` commands
Fixes #227

creating circleci orb for pluto

---

orb/commands/install.yml
orb/executors/default.yml
orb/jobs/detect.yml
orb/jobs/detect_files.yml
orb/scripts/install.sh

- install pluto command into cimg/base executor
closes #237

installing pluto command into cimg executor

---

orb/jobs/detect.yml
orb/scripts/detect.sh
orb/scripts/detect_files.sh

updating scripts to run pluto commands

---

orb/scripts/detect.sh
orb/scripts/detect_files.sh

bash scripts return proper exit code
closes #242

set -e so script exits with proper exit code

---

.circleci/config.yml
.goreleaser.yml

**Why This PR?**
Updates CI to use Cosign for signing all manifests, images, and the checksums file.
**Checklist:**

Use cosign to sign images and push to GCP artifact registry

---

.circleci/config.yml

**Why This PR?**
The docker login didn't work
**Checklist:**

Fix docker login for release

---

.circleci/config.yml
.goreleaser.yml

**Why This PR?**
- One of the cosign flag names has changed
- Wasn't installing vault, so publish docs is failing
**Checklist:**

Fix flags on cosign. Install vault for publishing docs

---

.circleci/config.yml

Install yq and vault in the publish docs step
I added to the aws cli install step and renamed it. Install multiple tools now
none

install tools for docs publishing

---

versions.yaml

This PR fixes issue #251
Update some replacement api versions
Add cronjob batch/v1
Add PDB policy/v1
Fix autoscaling/v2beta1 to be replaced by autoscaling/v2
n/a

Fix replacement versions for some APIs

---

versions.yaml

This PR fixes issue #258
See #258
Removed invalid version entry

Remove invalid istio version entry

---

.circleci/config.yml

Update goreleaser to 1.5.0

---

.circleci/config.yml
Makefile
e2e/tests/00_static_files.yaml

Test the new orb and getting temp aws credentials from vault so that we don't have to rotate IAM keys
Dev orb, new command
TODO:

Update docs publish step to use new standards

---

.circleci/config.yml

Circle is deprecating this functionality

Remove experimental features in build

---

.circleci/config.yml
Dockerfile
go.mod

Update alpine and other build dependencies

---

Dockerfile

Use the latest edge release to remove vulnerabilities
Remove vulnerabilities
Edit dockerfile
n/a

Update alpine to latest edge

---

cmd/root.go
docs/advanced.md

This PR fixes #460 
To add a way to suppress the footer note for scripts running pluto multiple times.
Simply added a flag to toggle the footer and modified the PersistentPostRun stage to reflect the changes
N/A

Suppress footer flag using --no-footer

---

README.md
docs/package-lock.json

Update the documentation from our vuepress template
./scripts/update-all.sh in the documentation-template repo

Update documentation from template

---

versions.yaml

Update based on https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
added some versions

Add flowcontrol deprecations

---

Makefile

The makefile was broken. I fix.
Point the build command to main.go

Fix the makefile for local dev

---

docs/faq.md

This PR fixes #495
Update FAQ with more details about false positives

Update FAQ with more details about last-applied-configuration issues

---

docs/advanced.md

This PR fixes #494
Update exit code docs to reflect new options

Fix the exit code documentation

---

docs/advanced.md

This PR fixes #501
Add docs
Added a note about escaping spaces in a shell command.

Add docs note about escaping spaces for column names

---

github-action/action.yml

Update to correct registry
Update github action
n/a

update the github action registry

---

Dockerfile

Update Alpine to 3.19

---

go.mod
go.sum

Bumped golang.org/x/net to v0.17.0 to fix HIGH vulnerabilities

---

.goreleaser.yml

fix typo in cosign command
re-added equals sign

re-added equals sign

---

.circleci/config.yml

fix(release): fix release; fix HIGH vulns

---

cmd/pluto/main.go
cmd/root.go
go.mod
go.sum
pkg/discovery-api/discovery_api.go
pkg/finder/finder.go
pkg/finder/finder_test.go
pkg/helm/helm.go
pkg/helm/helm_test.go

Removed pluto v5 references

---

.circleci/config.yml
go.mod

INSIGHTS-374 Pluto: bump go to 1.22.7

---

versions.yaml

This PR fixes #554
Update versions.yaml with the new removal.

feat: add flowcontrol v1beta2 removal in 1.32

---

Dockerfile

Bumped alpine to 3.21
