FairwindsOps/pluto

.circleci/config.yml, .goreleaser.yml, README.md
=> Adding brew tap to goreleaser. Update README with exit codes and homebrew.

README.md, cmd/root.go, e2e/tests/00_static_files.yaml, e2e/tests/01_helm-detect-3.yaml, e2e/tests/02_helm-detect-2.yaml, e2e/tests/03-cli-validation.yaml, pkg/api/output.go, pkg/api/output_test.go
I made the exit code `2` indicate a deprecation, and `1` indicate an error.
Fixes #49
=> Clarify exit codes. Allow filtering of json and yaml output by -A flag

pkg/api/versions.go
=> Add PriorityClass for v1.17.0

cmd/root.go, e2e/tests/00_static_files.yaml, pkg/api/list.go, pkg/api/list_test.go, pkg/api/output_test.go, pkg/api/versions.go
Fixes #66
Removed all omitempty on the json and yaml output for versions. The more I thought about it the more I think Luke is correct.
=> add options for list output to cover all our standard output options

pkg/helm/kube.go
Hi, here is PR for adding OIDC Auth Provider support.
When running `detect-helm` against IBMCloud I got following error:
```
Error creating kubernetes client: no Auth Provider found for name "oidc"
```
Thanks for this awesome project!
=> Support OIDC Auth Provider

pkg/api/versions.go, pkg/api/versions_test.go, pkg/helm/helm.go
This change allows the run of checks to continue if an error is encountered by an external package such as yaml or helm. For instance, if there is malformed yaml at any point it will log out the error and continue on to the next manifest instead of bailing out of the program completely.
This allows you to still get output of deprecated/removed apiVersions in other manifests and warn you that you are missing information for manifests with malformed yaml (or whatever other error it may encounter, such as helm mentioning there are `no deployed releases`
fixes #82
=> Better logging/ux for external errors

.circleci/config.yml, Dockerfile
Pluto doesn't have the `--output-file` function, but it also doesn't have a shell. We need one of these to enable Insights integration I think because Insights needs a generated report file. I removed all of the Scratch lines and left it on the alpine image.
=> remove Scratch layers

pkg/helm/helm.go
That helps us to better identify which release is problematic in the scenario of multiple releases with the same name across several namespaces.
=> Add release namespace to Helm-related errors

pkg/api/output.go, pkg/api/output_test.go
We're running
```
$ pluto detect-helm -ojson > /output/pluto.json;
```
When there are no deprecated resources in the cluster, this results in
```
$ cat /output/pluto.json
There were no apiVersions found that match our records.
```
which is not valid JSON
=> Fix JSON/YAML output when there are no outputs

cmd/root.go, e2e/tests/00_static_files.yaml, e2e/tests/03-cli-validation.yaml, pkg/api/columns.go, pkg/api/output.go, pkg/api/output_test.go
This should make dealing with columns easier. You define the interface of the column once, and then add it to the
proper output column list. Right now no output changes are made, just the underlying code to print them.
In theory, this will make implementing different output types easier.
Fixes #95
Paves the way for #96 by simply modifying the normalColumns and wideColumns functions.
=> Refactor output columns into interfaces. Add custom output option

e2e/tests/00_static_files.yaml, e2e/tests/01_helm-detect-3.yaml, pkg/api/columns.go, pkg/api/output.go, pkg/api/output_test.go, pkg/api/versions.go, pkg/api/versions_test.go, pkg/finder/finder.go, pkg/finder/finder_test.go
This adds filepath to the output if it is known. It is not included by default in any of the tabular outputs, but adds it as a column option. 
Filepath will be in the json and yaml output as well
Fixes #97 
Additional non-related changes:
- I removed the error handling from the containsStub function. There was no possible way it could return an error.
- Removed an unnecessary check for nil in the UnMarshalVersions function.
=> Add filepath as a possible custom column

README.md, cmd/root.go, e2e/tests/00_static_files.yaml, pkg/api/output.go, pkg/api/output_test.go
This flag will remove the outputs that are deprecated but not removed in the target version.
In the current implementation, this could affect exit code.
Fixes #96
=> Add --only-show-removed flag to filter outputs

cmd/root.go, go.mod, go.sum, main.go, pkg/finder/finder.go, pkg/finder/finder_test.go, pkg/helm/helm.go, pkg/helm/helm_test.go
Outside projects can only import Pluto v1 right now because of the way Go Mod handles Semver. This will fix it so v3 is importable.
=> Update imports for major version

pkg/api/versions.go, pkg/api/versions_test.go, pkg/helm/helm_test.go
Fixes #117
This changes a bit more behavior than I would like, but I think it's fine. Look carefully
=> Don't error if there are no apiVersions found

pkg/helm/helm.go
allows to programmatically creating helm client
for the given kube config
Fixes: #132 
Signed-off-by: Ishan Khare <ishankhare07@gmail.com>
=> add NewHelmWithKubeClient

versions.yaml
=> apiextensions.k8s.io/v1beta1 and admissionregistration.k8s.io/v1beta1  deprecated in 1.22

.circleci/config.yml, .goreleaser.yml
npm run check-links was in the wrong spot, and 386 was causing issues.
=> fix release

docs/installation.md
Add `asdf local pluto` which is missing in the installation.
Otherwise, it returns the following:
```
No version set for command pluto
Consider adding one of the following versions in your config file at
pluto 4.0.4
```
=> docs: Add missing asdf local pluto

README.md, docs/README.md
Link from https://pluto.docs.fairwinds.com/ to the [Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/) at https:\/\/k8s.io/docs/reference/using-api/deprecation-guide/
=> Link to Kubernetes deprecated API list

.pre-commit-config.yaml, cmd/root.go, go.mod, go.sum, pkg/api/output.go, pkg/api/output_test.go
Running with the flag `-omarkdown` will output a markdown formatted table for use in documentation.
=> feat: allow output to be formatted as a markdown table

go.mod, go.sum
This fixes CVE-2020-14040 as found by trivy (https://github.com/aquasecurity/trivy). There are other HIGHs without fixes available, and a MEDIUM in client-go but updating that probably isn't as easy.
=> chore: update golang.org/x/text to fix HIGH CVE CVE-2020-14040

versions.yaml
According to the [official docs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#priorityclass-v122):
> The scheduling.k8s.io/v1beta1 API version of PriorityClass will no longer be served in v1.22
Adjusted `versions.yaml` file to match.
=> Adjust removed-in version for PriorityClass

.github/workflows/github-action-test.yml, README.md, github-action/action.yml
I'd like to be able to use `pluto` as part of my github workflows. I did a quick google and couldn't find an action that already exists, so thought I'd contribute one.
It's very simple to run and basically just copies the released `pluto` binary into the runner.
=> added github action to install pluto

versions.yaml
Fixes #233
Pulled from https://kubernetes.io/docs/reference/using-api/deprecation-guide/
=> Add missing storage and apiregistration deprecations

versions.yaml
cert-manager deprecated the v1alpha2, v1alpha3 and v1beta1 versions in v1.4.0, and removed them in v1.6.0
Fixes #244
=> Add deprecated cert-manager versions

.circleci/config.yml
**Why This PR?**
Docker login failed on release. Neededa $ to reference variable
**Checklist:**
=> Missing $ in docker login

e2e/tests/00_static_files.yaml, e2e/tests/assets/list/list-deployment-deprecated-and-non-deprecated.yaml, e2e/tests/assets/list/list-deployment-non-deprecated.yaml, pkg/api/versions.go, pkg/api/versions_test.go
This PR fixes issue #255 
* [x ] I have signed the CLA
* [x ] I have updated/added any relevant documentation
Add parsing of manifests inside List objects, by expanding their content.
Added additional parsing logic.
This should be transparent to users, so I didn't do any change to the documentation, let me know if you want me to do any update
=> Add support for parsing manifests contained into List objects

.goreleaser.yml, docs/installation.md
This PR fixes #254
Document the use of cosign to sign images, and how to verify the signatures.
- Add to installation docs
- Add footer to releases
n/a
=> Document cosign, and add to release notes

cmd/root.go, docs/advanced.md, pkg/api/output.go, pkg/api/output_test.go
This PR fixes #278
The goal of this PR is to add another output option via the `--output` flag to be able to output CSV formatted data.
I added an extra output option called `csv` which will, if used, output data to `stdout` in CSV format.
N/A
=> Add CSV output option

versions.yaml
This PR fixes #280
Bugfix on replacement API for `autoscaling/v2beta2`
`autoscaling/v1` -> `autoscaling/v2`
None
=> `autoscaling/v2beta2` replacement should be `autoscaling/v2`

versions.yaml
see https://kubernetes.io/docs/reference/using-api/deprecation-guide/
This PR fixes #282 
Update and add missing versions of k8s components according to the Kubernetes documentation [Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/)
Update existing versions and add missing on the versions.yaml file.
=> fix/update versions according to k8s Deprecated API Migration Guide

versions.yaml
This PR fixes #286
Add removal of PodSecurityPolicy to versions.yaml
See diff
N/A
=> Add PodSecurityPolicy removal in kube v1.25

orb/commands/configure_env.yml, orb/commands/detect.yml, orb/commands/detect_files.yml, orb/examples/detect.yml, orb/examples/detect_files.yml, orb/jobs/detect.yml, orb/jobs/detect_files.yml, orb/scripts/detect.sh, orb/scripts/detect_files.sh
This PR fixes #285
Allow disabling the input parameters for configuration so that circle context can be used.
Added a configure_env command, and plumbed that into the jobs. This makes it so that config is always done via env vars, but the source of those vars can change.
=> Enable orb to use environment variables from context

e2e/tests/00_static_files.yaml, pkg/api/columns.go, pkg/api/output_test.go
Fixes https://github.com/FairwindsOps/pluto/issues/409
Replaces https://github.com/FairwindsOps/pluto/issues/408
This PR fixes the ordering of custom columns.
Iterate and append columns using user provided custom columns index instead of available columns index.
=> fix: preserve ordering of custom columns

cmd/root.go, docs/advanced.md, pkg/api/output.go, pkg/api/output_test.go, pkg/api/versions.go, pkg/api/versions_test.go
Allow hiding headers in output.
Add a `--no-headers` flag that hide headers in tab, markdown and csv outputs.
`pluto [snip] -ocsv | grep -v 'KIND,[snip]'`
=> feat: allow hiding headers in output

cmd/root.go, pkg/finder/finder.go
Fixed a linter error causing build to fail in Go 1.19 by removing deprecated io/ioutil functions and replacing them with their Go 1.16 counterparts.
This PR fixes #438
To allow compilation using Go 1.19, by replacing deprecated Go functions with their counterparts.
I changed "io/ioutil".ReadFile to os.ReadFile and "io/ioutil".ReadAll to os.ReadAll for all occurrences.
If backwards compatibility with Go versions prior to 1.16 is important for this project, a solution which vendors the dependency with version-specific calls should be favoured.
=> Fixed a linter error causing lack of compilation in Go 1.19

versions.yaml
This PR fixes #436 
Add the following deprecated.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#csistoragecapacity-v127
I have not used this resource, but have changed values.yaml because I thought the Issue was correct.
=> fix: add removed-in to storage.k8s.io/v1beta1.CSIStorageCapacity

cmd/root.go, docs/quickstart.md
Add a command to Pluto that combines all in-cluster detections - currently `detect-helm` and `detect-api-resources`.
```
$ ./pluto detect-all-in-cluster 2>/dev/null
NAME              KIND                VERSION                     REPLACEMENT            REMOVED   DEPRECATED  
badhelm/badhelm   Ingress             networking.k8s.io/v1beta1   networking.k8s.io/v1   true      true        
webapp            Ingress             networking.k8s.io/v1beta1   networking.k8s.io/v1   true      true        
webapp            Ingress             networking.k8s.io/v1beta1   networking.k8s.io/v1   true      true        
eks.privileged    PodSecurityPolicy   policy/v1beta1                                     false     true        
```
```
$ ./pluto detect-helm 2>/dev/null
NAME              KIND …
```
=> Add a `detect-all-in-cluster` command to run both `detect-helm` and `detect-api-resources`

e2e/tests/01_helm-detect-3.yaml, versions.yaml
ref: https://github.com/FairwindsOps/pluto/pull/452
Enable `replacement-available-in`.
I have set `replacement-available-in` with respect to what is presented in the following document
https://kubernetes.io/docs/reference/using-api/deprecation-guide/
I didn't add the ones that were not mentioned in the current versions.yaml. (e.g. `FlowSchema`)
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-29
=> add: set replacement-available-in to existing version.

versions.yaml
The current target version, 1.22, is super old. Let's go newer
Update target-versions in versions.yaml
n/a
=> update the default target version of k8s to v1.25

.circleci/config.yml, cmd/root.go, e2e/test.sh, e2e/tests/00_static_files.yaml, e2e/venom.0.log, e2e/venom.1.log, e2e/venom.log
This PR fixes #507
Fix bug with exit code handling
Fixed the bug, made the handling consistent, and added a test.
n/a
=> Fix exit code handling

pkg/api/output_test.go, pkg/api/versions.go, pkg/api/versions_test.go
Fixing logic for isReplacementAvailableIn  when field availableIn is empty
Updated isReplacementAvailableIn  function
=> Fixing isReplacementAvailableIn logic when field available in is empty

pkg/api/columns.go
These two were not included in `possibleColumns` and therefore running e.g. `pluto detect-files -o markdown --columns "REPL AVAIL"` would not actually print the column, despite no error being reported.
This PR fixes #514
Fix the above issue
Added the two columns in the `possibleColumns` slice
=> Fix using REPL AVAIL/REPL AVAIL IN as custom columns

versions.yaml
Fixes a typo in the versions.yaml file related to 1.29.0 FlowSchema deprecation.
Same as above.
=> Fix FlowSchema typo in versions.yaml

.circleci/config.yml, .goreleaser.yml
Bump goreleaser version to build Pluto with newer Go version
Build Pluto with a newer GO version due to vulnerabilities in Go 1.20.4
* Update goreleaser container image from 1.18.2 to 1.22.1
* Update `.goreleaser.yml` due to a [depreciation of `tap`](https://goreleaser.com/deprecations/?h=depre#brewstap) in goreleaser version 1.19.0
* I've used the goreleaser image locally to build Pluto and verify the build pass successfully.
* Verified Pluto binary for `Darwin` was built with newer GO version (1.21.3)
* Verified Pluto is running on a test cluster
=> Bump goreleaser version to 1.22.1

.goreleaser.yml
Release step is failing with;
error=sign: cosign failed: exit status 1: WARNING: the -output-signature=dist/checksums.txt.sig flag is deprecated and will be removed in a future release. Please use the --output-signature=dist/checksums.txt.sig flag instead.
Using payload from: dist/checksums.txt
This update uses the non-deprecated command and also accepts the sig.
* [*] I have signed the CLA
* [*] I have updated/added any relevant documentation
To fix the failing circleci build
Added in a -y to accept the signature and updated the deprecated -output-signature
Not looked at other options
=> Accept signature for cosign

.goreleaser.yml
changing `{artifact}` in `signs` cmd to `{digest}`
Fix the release step which is currently fails with error message
```
error=signing docker images: failed to publish artifacts: sign: cosign failed: exit status 1: WARNING: Image reference sha256:424fa83f860fe96d1966c0d1cab7c62fc06d36a2e763bad1d8ce004cca306ada uses a tag, not a digest, to identify the image to sign.
```
and
```
Error: signing [sha256:424fa83f860fe96d1966c0d1cab7c62fc06d36a2e763bad1d8ce004cca306ada]: accessing entity: GET https://index.docker.io/v2/library/sha256/manifests/424fa83f860fe96d1966c0d1cab7c62fc06d36a2e763bad1d8ce004cca306ada: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/sha256 Type:repository]]
main.go:74: error during command execution: signing …
```
=> fix(release): another attempt to fix the release step

cmd/pluto/main.go, cmd/root.go, go.mod, go.sum, pkg/discovery-api/discovery_api.go, pkg/finder/finder.go, pkg/finder/finder_test.go, pkg/helm/helm.go, pkg/helm/helm_test.go
=> Add pluto module v5 back

versions.yaml
This PR fixes #538
Add deprecation and removal checks for audit.k8s.io beta and alpha apiVersions.
Added entries in versions.yaml.
=> feat: add audit apiversion check

.circleci/config.yml, .goreleaser.yml, go.mod
This PR fixes #549 
Upgrade the version of Goreleaser following the [upgrade guide](https://goreleaser.com/blog/goreleaser-v2/#upgrading)
- Use most recent release of Go `v1.22`
- Modify `.goreleaser.yml` to use new v2 syntax
Remaining on deprecated version
=> fix(release): update goreleaser to 2.2.0

.idea/workspace.xml, go.mod
This PR is intended to bump the GO version `from: 1.22.7` `to: 1.23.1` in order to resolve the following CVE's:
-----
1. CVE-2024-45336
2. CVE-2024-45341
Changed the GO version in go.mod
N/A
=> Bump-Go-version-to-1.23.1

.circleci/config.yml, Dockerfile, go.mod
=> INS-1146: Fix CVE-2025-22874 for pluto
